### ISSUE TITLE
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application

### ISSUE THREAD

**Issue by ech0s7r** [jwzhuang/Android_H264Stream#2]
Running on Android 6 and clicking on “Start Camera” button, i get this error:

11-04 12:34:09.254: E/AndroidRuntime(23968): java.lang.RuntimeException: Unable to create service tw.jwzhuang.ipcam.RecordService: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
11-04 12:34:09.254: E/AndroidRuntime(23968):    at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at android.app.ActivityThread.-wrap4(ActivityThread.java)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at android.os.Handler.dispatchMessage(Handler.java:102)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at android.os.Looper.loop(Looper.java:148)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at android.app.ActivityThread.main(ActivityThread.java:5417)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at java.lang.reflect.Method.invoke(Native Method)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-04 12:34:09.254: E/AndroidRuntime(23968): Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
11-04 12:34:09.254: E/AndroidRuntime(23968):    at android.view.ViewRootImpl.setView(ViewRootImpl.java:571)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at tw.jwzhuang.ipcam.RecordService.createView(RecordService.java:146)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at tw.jwzhuang.ipcam.RecordService.onCreate(RecordService.java:108)
11-04 12:34:09.254: E/AndroidRuntime(23968):    at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
11-04 12:34:09.254: E/AndroidRuntime(23968):    ... 8 more

I have tried to add this permission to Manifest (android.permission.SYSTEM_ALERT_WINDOW), but i still get the same error.
I think the problem is in RecordService.java creating the View using WindowManger.addView() function.

**Comment by jwzhuang** [comment]
add permission  android.permission.SYSTEM_ALERT_WINDOW 
and modify WindowManager.LayoutParams type to WindowManager.LayoutParams.TYPE_SYSTEM_ALERT or WindowManager.LayoutParams.TYPE_PHONE . It will fix the error.

But this app is old, I write this in nexus 5 + android 4.x, maybe not work in android 6
You can google "Mediarecorder" + "LocalSocket" to find discuss
